"""update tenant

Revision ID: 3859f5017782
Revises: 81aaa72d2fb3
Create Date: 2026-07-25 15:30:48.902709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3859f5017782'
down_revision = '81aaa72d2fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_constraint(op.f('tenants_tenant_id_fkey'), 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tenants_tenant_id_fkey'), 'tenants', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
