"""Enforce global tenant isolation

Revision ID: 81aaa72d2fb3
Revises: 110b5591f853
Create Date: 2026-07-25 15:06:46.274987

"""
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '81aaa72d2fb3'
down_revision = '110b5591f853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('tenants',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('storage_quota_gb', sa.Float(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    op.create_table('ai_feedback_metrics',
    sa.Column('time_bucket', sa.DateTime(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('total_extractions', sa.Integer(), nullable=False),
    sa.Column('total_corrections', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('error_pattern_distribution', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_metrics_field_name'), 'ai_feedback_metrics', ['field_name'], unique=False)
    op.create_index(op.f('ix_ai_feedback_metrics_tenant_id'), 'ai_feedback_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_metrics_time_bucket'), 'ai_feedback_metrics', ['time_bucket'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=True),
    sa.Column('time_bucket', sa.DateTime(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_dimension'), 'analytics_snapshots', ['dimension'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_metric_name'), 'analytics_snapshots', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_tenant_id'), 'analytics_snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_time_bucket'), 'analytics_snapshots', ['time_bucket'], unique=False)
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_secret', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('backup_configs',
    sa.Column('schedule_cron', sa.String(length=50), nullable=False),
    sa.Column('destination_bucket', sa.String(length=150), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_configs_tenant_id'), 'backup_configs', ['tenant_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('target_tenants', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_is_enabled'), 'feature_flags', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_tenant_id'), 'knowledge_bases', ['tenant_id'], unique=False)
    op.create_table('learning_datasets',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('target_field', sa.String(length=100), nullable=True),
    sa.Column('min_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('export_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_datasets_dataset_type'), 'learning_datasets', ['dataset_type'], unique=False)
    op.create_index(op.f('ix_learning_datasets_tenant_id'), 'learning_datasets', ['tenant_id'], unique=False)
    op.create_table('prompt_optimization_records',
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('few_shot_exemplars', sa.JSON(), nullable=True),
    sa.Column('eval_accuracy_score', sa.Float(), nullable=True),
    sa.Column('eval_sample_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_optimization_records_is_active'), 'prompt_optimization_records', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_optimization_records_prompt_name'), 'prompt_optimization_records', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_prompt_optimization_records_tenant_id'), 'prompt_optimization_records', ['tenant_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('max_processing_time_seconds', sa.Integer(), nullable=False),
    sa.Column('target_compliance_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_policies_document_type'), 'sla_policies', ['document_type'], unique=True)
    op.create_index(op.f('ix_sla_policies_is_active'), 'sla_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_sla_policies_tenant_id'), 'sla_policies', ['tenant_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_index(op.f('ix_system_configs_tenant_id'), 'system_configs', ['tenant_id'], unique=False)
    op.create_table('validation_rules',
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('constraint_value', sa.Text(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_field_name'), 'validation_rules', ['field_name'], unique=False)
    op.create_index(op.f('ix_validation_rules_is_enabled'), 'validation_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_validation_rules_tenant_id'), 'validation_rules', ['tenant_id'], unique=False)
    op.create_table('document_layout_blocks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_layout_blocks_tenant_id'), 'document_layout_blocks', ['tenant_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_tenant_id'), 'document_pages', ['tenant_id'], unique=False)
    op.create_table('document_tables',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('table_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tables_tenant_id'), 'document_tables', ['tenant_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('buyer', sa.String(length=100), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_chunk_id'), 'knowledge_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.create_table('learning_correction_records',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('buyer_code', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_extracted_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('was_modified', sa.Boolean(), nullable=False),
    sa.Column('initial_confidence', sa.Float(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('ocr_context_snippet', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['review_fields.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_correction_records_buyer_code'), 'learning_correction_records', ['buyer_code'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_document_id'), 'learning_correction_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_document_type'), 'learning_correction_records', ['document_type'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_field_id'), 'learning_correction_records', ['field_id'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_field_name'), 'learning_correction_records', ['field_name'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_reviewer_id'), 'learning_correction_records', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_session_id'), 'learning_correction_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_tenant_id'), 'learning_correction_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_learning_correction_records_was_modified'), 'learning_correction_records', ['was_modified'], unique=False)
    op.create_table('learning_dataset_items',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('correction_record_id', sa.Uuid(), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('target_output', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['correction_record_id'], ['learning_correction_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['learning_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_dataset_items_correction_record_id'), 'learning_dataset_items', ['correction_record_id'], unique=False)
    op.create_index(op.f('ix_learning_dataset_items_dataset_id'), 'learning_dataset_items', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_learning_dataset_items_tenant_id'), 'learning_dataset_items', ['tenant_id'], unique=False)
    op.alter_column('ai_provider_configs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'ai_provider_configs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('ai_provider_routing_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'ai_provider_routing_rules', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('approvals', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'approvals', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('document_extractions', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'document_extractions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('document_versions', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'document_versions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('erp_transactions', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'erp_transactions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('events', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'events', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('extraction_metrics', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'extraction_metrics', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('field_corrections', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'field_corrections', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('jobs', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'jobs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_brands', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_brands', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_buyers', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_buyers', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_colors', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_colors', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_fabrics', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_fabrics', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_sizes', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_sizes', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_suppliers', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_suppliers', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('md_uoms', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'md_uoms', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('projects', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('review_comments', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'review_comments', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('review_fields', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'review_fields', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('review_history', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'review_history', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('review_sessions', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'review_sessions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('reviews', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'reviews', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(), postgresql_using='tenant_id::uuid',
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'review_sessions', type_='foreignkey')
    op.alter_column('review_sessions', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'review_history', type_='foreignkey')
    op.alter_column('review_history', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'review_fields', type_='foreignkey')
    op.alter_column('review_fields', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.alter_column('review_comments', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_uoms', type_='foreignkey')
    op.alter_column('md_uoms', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_suppliers', type_='foreignkey')
    op.alter_column('md_suppliers', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_sizes', type_='foreignkey')
    op.alter_column('md_sizes', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_fabrics', type_='foreignkey')
    op.alter_column('md_fabrics', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_colors', type_='foreignkey')
    op.alter_column('md_colors', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_buyers', type_='foreignkey')
    op.alter_column('md_buyers', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'md_brands', type_='foreignkey')
    op.alter_column('md_brands', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'field_corrections', type_='foreignkey')
    op.alter_column('field_corrections', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'extraction_metrics', type_='foreignkey')
    op.alter_column('extraction_metrics', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'erp_transactions', type_='foreignkey')
    op.alter_column('erp_transactions', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.alter_column('document_versions', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'document_extractions', type_='foreignkey')
    op.alter_column('document_extractions', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.alter_column('approvals', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'ai_provider_routing_rules', type_='foreignkey')
    op.alter_column('ai_provider_routing_rules', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_constraint(None, 'ai_provider_configs', type_='foreignkey')
    op.alter_column('ai_provider_configs', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50), postgresql_using='tenant_id::varchar',
               existing_nullable=True)
    op.drop_index(op.f('ix_learning_dataset_items_tenant_id'), table_name='learning_dataset_items')
    op.drop_index(op.f('ix_learning_dataset_items_dataset_id'), table_name='learning_dataset_items')
    op.drop_index(op.f('ix_learning_dataset_items_correction_record_id'), table_name='learning_dataset_items')
    op.drop_table('learning_dataset_items')
    op.drop_index(op.f('ix_learning_correction_records_was_modified'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_tenant_id'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_session_id'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_reviewer_id'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_field_name'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_field_id'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_document_type'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_document_id'), table_name='learning_correction_records')
    op.drop_index(op.f('ix_learning_correction_records_buyer_code'), table_name='learning_correction_records')
    op.drop_table('learning_correction_records')
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_chunk_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_document_tables_tenant_id'), table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_pages_tenant_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_layout_blocks_tenant_id'), table_name='document_layout_blocks')
    op.drop_table('document_layout_blocks')
    op.drop_index(op.f('ix_validation_rules_tenant_id'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_is_enabled'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_field_name'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_system_configs_tenant_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_category'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sla_policies_tenant_id'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_is_active'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_document_type'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_prompt_optimization_records_tenant_id'), table_name='prompt_optimization_records')
    op.drop_index(op.f('ix_prompt_optimization_records_prompt_name'), table_name='prompt_optimization_records')
    op.drop_index(op.f('ix_prompt_optimization_records_is_active'), table_name='prompt_optimization_records')
    op.drop_table('prompt_optimization_records')
    op.drop_index(op.f('ix_learning_datasets_tenant_id'), table_name='learning_datasets')
    op.drop_index(op.f('ix_learning_datasets_dataset_type'), table_name='learning_datasets')
    op.drop_table('learning_datasets')
    op.drop_index(op.f('ix_knowledge_bases_tenant_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_is_enabled'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_backup_configs_tenant_id'), table_name='backup_configs')
    op.drop_table('backup_configs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_analytics_snapshots_time_bucket'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_tenant_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_metric_name'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_dimension'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_ai_feedback_metrics_time_bucket'), table_name='ai_feedback_metrics')
    op.drop_index(op.f('ix_ai_feedback_metrics_tenant_id'), table_name='ai_feedback_metrics')
    op.drop_index(op.f('ix_ai_feedback_metrics_field_name'), table_name='ai_feedback_metrics')
    op.drop_table('ai_feedback_metrics')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
